const surahNames = {
  1: [
    "al-fatiha",
    "al-fateya",
    "al-fatiyha",
    "al-fatiya",
    "fatiha",
    "fateya",
    "fatiyha",
    "fatiya",
  ],
  2: [
    "al-baqarah",
    "al-baqarah",
    "al-baqara",
    "al-baqra",
    "baqarah",
    "baqara",
    "baqra",
    "baqrah",
  ],
  3: ["al-imran", "imran", "alay-imran"],
  4: [
    "an-nisa",
    "al-nisa",
    "al-nesa",
    "al-neesa",
    "nesa",
    "neesa",
    "nisa",
    "annisa",
    "annesa",
    "anneesa",
  ],
  5: ["al-maidah", "al-mayedha", "al-miadha", "maidah", "mayedha", "miadha"],
  6: ["al-anam", "al-aname", "anam", "aname"],
  7: ["al-araf", "araf"],
  8: ["al-anfal", "anfal"],
  9: [
    "at-tawbah",
    "al-tawbah",
    "al-tooba",
    "al-towba",
    "al-taobha",
    "al-toaba",
    "tawbah",
    "tawbah",
    "tooba",
    "towba",
    "taobha",
    "toaba",
    "attawbah",
    "attooba",
    "attowba",
    "attoabha",
    "attoaba",
  ],
  10: ["al-yunus", "al-yones", "al-younes", "yunus", "yones", "younes"],
  11: ["al-hud", "al-hood", "al-hoad", "hud", "hood", "hoad"],
  12: [
    "al-yusuf",
    "al-yousuf",
    "al-yousaf",
    "al-yoasaf",
    "yusuf",
    "yousuf",
    "yousaf",
    "yoasaf",
  ],
  13: [
    "ar-rad",
    "ar-raad",
    "al-rad",
    "al-raad",
    "rad",
    "raad",
    "rad",
    "raad",
    "arrad",
  ],
  14: [
    "al-ibrahim",
    "al-ibraheem",
    "al-ibraheam",
    "al-ibrahem",
    "ibrahim",
    "ibraheem",
    "ibraheam",
    "ibrahem",
  ],
  15: ["al-hijr", "al-hejar", "al-hejr", "hijr", "hejar", "hejr"],
  16: ["an-nahl", "an-nahal", "al-nahl", "al-nahal", "annahl", "annahal"],
  17: ["al-isra", "al-esra", "isra", "esra"],
  18: [
    "al-kahf",
    "al-kahaf",
    "al-kaaf",
    "al-kaf",
    "kahf",
    "kahaf",
    "kaaf",
    "kaf",
  ],
  19: [
    "al-maryam",
    "al-mauryam",
    "al-maryum",
    "al-mariyam",
    "al-mariyum",
    "maryam",
    "mauryam",
    "maryum",
    "mariyam",
    "mariyum",
  ],
  20: ["al-taha", "al-taahaa", "al-taaha", "taha", "taahaa", "taaha"],
  21: [
    "al-anbiya",
    "al-ambiya",
    "al-anbeya",
    "al-ambeya",
    "anbiya",
    "ambiya",
    "anbeya",
    "ambeya",
  ],
  22: [
    "al-hajj",
    "al-haj",
    "al-haaj",
    "al-hag",
    "al-haag",
    "hajj",
    "haj",
    "haaj",
    "hag",
    "haag",
  ],
  23: [
    "al-muminun",
    "al-momenon",
    "al-momenoon",
    "al-mumenun",
    "al-momenum",
    "al-momean",
    "al-momen",
    "al-mumin",
    "al-mumen",
    "muminun",
    "momenon",
    "momenoon",
    "mumenun",
    "momenum",
    "momean",
    "momen",
    "mumin",
    "mumen",
  ],
  24: [
    "an-nur",
    "an-noor",
    "an-nor",
    "al-nur",
    "al-noor",
    "al-nor",
    "nur",
    "noor",
    "nor",
  ],
  25: ["al-furqan", "al-forqan", "al-forkan", "furqan", "forqan", "forkan"],
  26: [
    "al-ashshuara",
    "al-ashura",
    "al-ashora",
    "al-shuara",
    "al-shura",
    "al-shora",
    "ashshuara",
    "ashura",
    "ashora",
    "shuara",
    "shura",
    "shora",
  ],
  27: [
    "an-naml",
    "an-namal",
    "al-naml",
    "al-namal",
    "annaml",
    "annamal",
    "naml",
    "namal",
  ],
  28: [
    "al-qasas",
    "al-kasas",
    "al-qases",
    "al-kases",
    "qasas",
    "kasas",
    "qases",
    "kases",
  ],
  29: [
    "al-ankabut",
    "al-ankabot",
    "al-ankaboot",
    "ankabut",
    "ankabot",
    "ankaboot",
  ],
  30: [
    "al-arrum",
    "al-aroom",
    "al-rum",
    "al-room",
    "arrum",
    "aroom",
    "rum",
    "room",
  ],
  31: [
    "al-luqmaan",
    "al-luqman",
    "al-loqman",
    "al-loqmaan",
    "al-lukman",
    "al-lokman",
    "al-lukmaan",
    "luqmaan",
    "luqman",
    "loqman",
    "loqmaan",
    "lukman",
    "lokman",
    "lukmaan",
  ],
  32: ["as-sajda", "as-sajada", "al-sajda", "al-sajada", "sajda", "sajada"],
  33: ["al-ahzaab", "al-ahzab", "ahzaab", "ahzab"],
  34: ["al-saba", "al-asaba", "saba", "asaba"],
  35: [
    "al-faatir",
    "al-fatir",
    "al-faater",
    "al-fater",
    "faatir",
    "fatir",
    "faater",
    "fater",
  ],
  36: ["al-yaseen", "al-yasen", "yaseen", "yasen"],
  37: [
    "al-assaaffaat",
    "al-assafat",
    "al-safat",
    "assaaffaat",
    "assafat",
    "safat",
  ],
  38: ["al-saad", "al-soad", "saad", "soad"],
  39: [
    "al-azzumar",
    "al-azumar",
    "al-azoomar",
    "al-azomar",
    "al-zzumar",
    "al-zumar",
    "al-zoomar",
    "al-zomar",
    "azzumar",
    "azumar",
    "azoomar",
    "azomar",
    "zzumar",
    "zumar",
    "zoomar",
    "zomar",
  ],
  40: [
    "al-ghafir",
    "al-gafir",
    "al-ghafer",
    "al-gafer",
    "ghafir",
    "gafir",
    "ghafer",
    "gafer",
  ],
  41: [
    "al-fussilat",
    "al-fusilat",
    "al-fossilat",
    "al-fosilat",
    "al-foselat",
    "fussilat",
    "fusilat",
    "fossilat",
    "fosilat",
    "foselat",
  ],
  42: [
    "al-ashshooraa",
    "al-ashora",
    "al-shora",
    "ashshooraa",
    "ashora",
    "shora",
  ],
  43: [
    "al-azzukhruf",
    "al-azukhruf",
    "al-azkhoraf",
    "al-zukhruf",
    "al-ukhruf",
    "al-khoraf",
    "azzukhruf",
    "azukhruf",
    "azkhoraf",
    "zukhruf",
    "ukhruf",
    "khoraf",
  ],
  44: [
    "al-addukhaan",
    "al-adukhaan",
    "al-adukhan",
    "al-dukhaan",
    "al-dukhaan",
    "al-dukhan",
    "dukhaan",
    "dukhaan",
    "dukhan",
    "addukhaan",
    "adukhaan",
    "adukhan",
  ],
  45: [
    "al-jaathiyah",
    "al-jatiha",
    "al-jathiha",
    "al-jateha",
    "jaathiyah",
    "jatiha",
    "jathiha",
    "jateha",
  ],
  46: [
    "al-ahqaaf",
    "al-ahqaf",
    "al-ahkaaf",
    "al-ahkaf",
    "ahqaaf",
    "ahqaf",
    "ahkaaf",
    "ahkaf",
  ],
  47: [
    "al-muhammad",
    "al-muhamad",
    "al-mohammad",
    "al-mohamad",
    "muhammad",
    "muhamad",
    "mohammad",
    "mohamad",
  ],
  48: ["al-fath", "fath"],
  49: [
    "al-hujuraat",
    "al-hujurat",
    "al-hojrat",
    "al-hojraat",
    "hujuraat",
    "hujurat",
    "hojrat",
    "hojraat",
  ],
  50: ["al-qaaf", "al-qaf", "qaaf", "qaf"],
  51: [
    "al-adhdhaariyaat",
    "al-adhdhariyat",
    "al-adhariyat",
    "al-azhdhaariyaat",
    "al-azhdhariyat",
    "al-azhariyat",
    "adhdhaariyaat",
    "adhdhariyat",
    "adhariyat",
    "azhdhaariyaat",
    "azhdhariyat",
    "azhariyat",
  ],
  52: [
    "al-attoor",
    "al-attor",
    "al-atoor",
    "al-ator",
    "al-toor",
    "al-tor",
    "attoor",
    "attor",
    "atoor",
    "ator",
    "toor",
    "tor",
  ],
  53: [
    "al-annajm",
    "al-anajm",
    "al-anajam",
    "al-najam",
    "al-njam",
    "annajm",
    "anajm",
    "anajam",
    "najam",
    "njam",
  ],
  54: ["al-qamar", "qamar"],
  55: [
    "ar-rahman",
    "al-arrahman",
    "al-arahman",
    "al-rahman",
    "rahman",
    "arrahman",
    "arahman",
    "rahman",
  ],
  56: [
    "al-waqia",
    "al-wakia",
    "al-wakeya",
    "al-waqeya",
    "waqia",
    "wakia",
    "wakeya",
    "waqeya",
  ],
  57: ["al-hadeed", "al-haded", "hadeed", "haded"],
  58: [
    "al-mujadila",
    "al-mojadila",
    "al-mojadala",
    "al-mujadala",
    "mujadila",
    "mojadila",
    "mojadala",
    "mujadala",
  ],
  59: ["al-hashr", "al-hashar", "hashr", "hashar"],
  60: [
    "al-mumtahanah",
    "al-momtahanah",
    "al-mumtahana",
    "al-momtahana",
    "al-motahana",
    "mumtahanah",
    "momtahanah",
    "mumtahana",
    "momtahana",
    "motahana",
  ],
  61: [
    "as-saff",
    "al-assaff",
    "al-asaff",
    "al-asaf",
    "al-saaf",
    "al-saff",
    "saff",
    "assaff",
    "asaff",
    "asaf",
    "saaf",
    "saff",
  ],
  62: ["al-jumuah", "al-jumha", "al-jomha", "jumuah", "jumha", "jomha"],
  63: [
    "al-munafiqoon",
    "al-munafiqon",
    "al-munafikoon",
    "al-munafikon",
    "al-monafiqoon",
    "al-monafiqon",
    "al-monafikoon",
    "al-monafikon",
    "munafiqoon",
    "munafiqon",
    "munafikoon",
    "munafikon",
    "monafiqoon",
    "monafiqon",
    "monafikoon",
    "monafikon",
  ],
  64: [
    "at-taghabun",
    "al-attaghabun",
    "al-ataghabun",
    "al-ataghaboon",
    "al-ataghabon",
    "al-taghabun",
    "al-taghabun",
    "al-taghaboon",
    "al-taghabon",
    "taghabun",
    "attaghabun",
    "ataghabun",
    "ataghaboon",
    "ataghabon",
    "taghabun",
    "taghabun",
    "taghaboon",
    "taghabon",
  ],
  65: [
    "at-talaq",
    "at-talak",
    "al-attalaq",
    "al-atalaq",
    "al-talaq",
    "al-talak",
    "talaq",
    "talak",
    "attalaq",
    "atalaq",
    "talaq",
    "talak",
  ],
  66: [
    "at-tahreem",
    "at-tahrem",
    "al-attahreem",
    "al-attahrem",
    "al-atahreem",
    "al-atahrem",
    "al-atahream",
    "al-tahreem",
    "al-thaream",
    "tahreem",
    "tahrem",
    "attahreem",
    "attahrem",
    "atahreem",
    "atahrem",
    "atahream",
    "tahreem",
    "thaream",
  ],
  67: ["al-mulk", "al-molak", "al-mulak", "mulk", "molak", "mulak"],
  68: ["al-qalam", "al-kalam", "qalam", "kalam"],
  69: [
    "al-haaqqa",
    "al-haqqa",
    "al-haaqa",
    "al-haqa",
    "haaqqa",
    "haqqa",
    "haaqa",
    "haqa",
  ],
  70: [
    "al-maarij",
    "al-marij",
    "al-maaraj",
    "al-maraj",
    "al-meraj",
    "maarij",
    "marij",
    "maaraj",
    "maraj",
    "meraj",
  ],
  71: ["al-nooh", "al-noah", "nooh", "noah"],
  72: ["al-jinn", "al-jin", "jinn", "jin"],
  73: [
    "al-muzzammil",
    "al-muzzamil",
    "al-muzammil",
    "al-muzamil",
    "al-muzamel",
    "muzzammil",
    "muzzamil",
    "muzammil",
    "muzamil",
    "muzamel",
  ],
  74: [
    "al-muddaththir",
    "al-mudaththir",
    "al-mudaseer",
    "al-mudaser",
    "al-mudasear",
    "muddaththir",
    "mudaththir",
    "mudaseer",
    "mudaser",
    "mudasear",
  ],
  75: [
    "al-qiyamah",
    "al-qiyamh",
    "al-qiyamat",
    "al-qiyamat",
    "qiyamah",
    "qiyamh",
    "qiyamat",
    "qiyamat",
  ],
  76: ["al-insaan", "al-insan", "al-dahar", "insaan", "insan", "dahar"],
  77: ["al-mursalaat", "al-mursalat", "mursalaat", "mursalat"],
  78: ["an-naba", "al-annaba", "al-anaba", "naba", "annaba", "anaba"],
  79: [
    "an-naaziaat",
    "an-naaziat",
    "an-naziaat",
    "an-naziat",
    "al-annaaziaat",
    "al-anaaziat",
    "al-anaziaat",
    "al-anaziat",
    "al-naaziaat",
    "al-naaziat",
    "al-naziaat",
    "al-naziat",
    "annaaziaat",
    "anaaziat",
    "anaziaat",
    "anaziat",
    "naaziaat",
    "naaziat",
    "naziaat",
    "naziat",
  ],
  80: ["al-abasa", "abasa"],
  81: [
    "at-takweer",
    "at-takwer",
    "at-takwear",
    "al-attakweer",
    "al-atakwer",
    "al-atakwear",
    "al-takweer",
    "al-takwer",
    "al-takwear",
    "attakweer",
    "atakwer",
    "atakwear",
    "takweer",
    "takwer",
    "takwear",
  ],
  82: ["al-infitar", "al-infetar", "infitar", "infetar"],
  83: [
    "al-mutaffifeen",
    "al-mutaffifen",
    "al-mutafifeen",
    "al-mutafifen",
    "al-mutafeafen",
    "al-mutafefean",
    "mutaffifeen",
    "mutaffifen",
    "mutafifeen",
    "mutafifen",
    "mutafeafen",
    "mutafefean",
  ],
  84: [
    "al-inshiqaaq",
    "al-inshiqaq",
    "al-inshaq",
    "inshiqaaq",
    "inshiqaq",
    "inshaq",
  ],
  85: [
    "al-burooj",
    "al-buroj",
    "al-borooj",
    "al-boroj",
    "al-boarooj",
    "al-boroaj",
    "burooj",
    "buroj",
    "borooj",
    "boroj",
    "boarooj",
    "boroaj",
  ],
  86: ["at-taariq", "at-tariq", "al-ataariq", "al-atariq", "ataariq", "atariq"],
  87: ["al-alaa", "al-ala", "alaa", "ala"],
  88: [
    "al-ghaashiyah",
    "al-ghashiyah",
    "al-ghashiya",
    "ghaashiyah",
    "ghashiyah",
    "ghashiya",
  ],
  89: ["al-fajr", "al-fajar", "fajr", "fajar"],
  90: ["al-balad", "balad"],
  91: [
    "ash-shams",
    "al-ashshams",
    "al-ashshamas",
    "al-shamas",
    "al-shams",
    "al-shamas",
    "ashshams",
    "ashshamas",
    "shamas",
    "shams",
    "shamas",
  ],
  92: ["al-layl", "al-layal", "layl", "layal"],
  93: [
    "ad-dhuha",
    "al-addhuha",
    "al-azdhuha",
    "al-azuha",
    "al-zuha",
    "dhuha",
    "addhuha",
    "azdhuha",
    "azuha",
    "zuha",
  ],
  94: [
    "ash-sharh",
    "al-ashrah",
    "al-ashra",
    "al-inshirah",
    "ashsharh",
    "ashrah",
    "ashra",
    "inshirah",
  ],
  95: [
    "at-teen",
    "at-tean",
    "al-atean",
    "al-ateen",
    "al-teen",
    "al-tean",
    "atean",
    "ateen",
    "teen",
    "tean",
  ],
  96: ["al-alaq", "al-alak", "alaq", "alak"],
  97: ["al-qadr", "al-qadar", "qadr", "qadar"],
  98: [
    "al-bayyinahh",
    "al-bayyinah",
    "al-bayinahh",
    "al-bayinah",
    "al-bayenah",
    "bayyinahh",
    "bayyinah",
    "bayinahh",
    "bayinah",
    "bayenah",
  ],
  99: [
    "az-zalzalah",
    "al-azzalzalah",
    "al-azalzalah",
    "al-zalzalah",
    "azzalzalah",
    "azalzalah",
    "zalzalah",
  ],
  100: [
    "al-aadiyaat",
    "al-adiyaat",
    "al-aadiyat",
    "al-adiyat",
    "aadiyaat",
    "adiyaat",
    "aadiyat",
    "adiyat",
  ],
  101: [
    "al-qaariah",
    "al-qariah",
    "al-qariyah",
    "al-qareyah",
    "qaariah",
    "qariah",
    "qariyah",
    "qareyah",
  ],
  102: [
    "at-takaathur",
    "at-takathur",
    "at-takasur",
    "al-atakaathur",
    "al-attakathur",
    "al-attakasur",
    "atakaathur",
    "attakathur",
    "attakasur",
  ],
  103: ["al-asr", "al-asar", "asr", "asar"],
  104: ["al-humazah", "al-humaza", "humazah", "humaza"],
  105: ["al-feel", "al-feal", "feel", "feal"],
  106: ["al-quraysh", "al-qurash", "al-qarash", "quraysh", "qurash", "qarash"],
  107: [
    "al-maaoon",
    "al-maaon",
    "al-maoon",
    "al-maon",
    "al-maun",
    "maaoon",
    "maaon",
    "maoon",
    "maon",
    "maun",
  ],
  108: [
    "al-kawthar",
    "al-Qawthar",
    "al-kawsar",
    "al-kosar",
    "al-qosar",
    "kawthar",
    "Qawthar",
    "kawsar",
    "kosar",
    "qosar",
  ],
  109: [
    "al-kaafiroon",
    "al-kafiroon",
    "al-kaafiron",
    "al-kafiron",
    "kaafiroon",
    "kafiroon",
    "kaafiron",
    "kafiron",
  ],
  110: [
    "an-nasr",
    "an-nasar",
    "al-annasr",
    "al-anasr",
    "al-nasr",
    "al-nasar",
    "annasr",
    "anasr",
    "nasr",
    "nasar",
  ],
  111: ["al-masad", "masad"],
  112: ["al-ikhlaas", "al-ikhlas", "ikhlaas", "ikhlas"],
  113: ["al-falaq", "al-falak", "falaq", "falak"],
  114: ["al-naas", "al-nas", "naas", "nas"],
};

module.exports = surahNames;
